FRUIT_MAPPING = {

    "Apple": "apple",
    "Banana": "banana",
    "Orange": "orange",
    "Mango": "mango",
    "Papaya": "papaya",
    "Guava": "guava",
    "Watermelon": "watermelon",
    "Muskmelon": "muskmelon",
    "Pomegranate": "pomegranate",
    "Grapes": "grapes",
    "Kiwi": "kiwi",
    "Strawberry": "strawberry",
    "Blueberry": "blue_berry",
    "Plum": "plum",
    "Plum Mango": "plum_mango",
    "Passion Fruit": "passionfruit",
    "Litchi": "litchi",
    "Lychee": "lychee",
    "Jamun": "jammun",
    "Pear": "pear",
    "Peach": "peach",
    "Pineapple": "pineapple",
    "Custard Apple": "custard_apple",
    "Dragon Fruit": "dragon_fruit",
    "Avocado": "avocado",
    "Sapota": "sapota",
    "Tender Coconut": "tender_coconut"
}