VEGETABLE_MAPPING = {

    "Onion": "onion",
    "Tomato": "tomato",
    "Potato": "potato",
    "Carrot": "carrot",
    "Beans": "beans",
    "Brinjal": "brinjal",
    "Cabbage": "cabbage",
    "Cauliflower": "cauliflower",
    "Cucumber": "cucumber",
    "Chilli": "chilli",
    "Drumstick": "drumstick",
    "Okra": "okra",
    "Lady Finger": "okra",
    "Bottle Guard":"bottle_gourd",
    "Bottle Gourd":"bottle_gourd",
    "Bottle Gourd,":"bottle_gourd",
    "Bitter Gourd": "hagalkai",
    "Snake Gourd": "snake_gourd",
    "Ridge Gourd": "ridge_gourd",
    "Ash Gourd": "ash_gourd",
    "Pumpkin": "pumpkin",
    "Capsicum": "capsicum",
    "Beetroot": "beetroot",
    "Radish": "radish",
    "Green Peas": "peas",
    "Sweet Corn": "sweet_corn",
    "Spinach": "greens",
    "Spinach (Palak)": "greens",
    "Fenugreek Leaves": "methi",
    "Coriander Leaves": "coriander",
    "Mint Leaves": "mint",
    "Curry Leaves": "curry_leaves",
    "Spring Onion": "spring_onion",
    "Broccoli": "broccoli",
    "Mushroom": "mushroom",
    "Raw Banana": "raw_banana",
    "Yam": "yam",
    "Colocasia": "colocasia",
    "Cluster Beans": "cluster_beans",
    "French Beans": "beans",
    "Zucchini": "zukkini",
    "Chayote Squash": "chayote_squash"
}