ZONE_MAP = {
    "akshayanagar": "South",
    "anjanapura": "South",
    "arehalli": "South",
    "banashankari": "South",
    "bannerghatta": "South",
    "bannerghatta road": "South",
    "basavanagudi": "South",
    "begur": "South",
    "bommanahalli": "South",
    "btm": "South",
    "btm layout": "South",
    "chandapura": "South",
    "chandhapura": "South",
    "singasandra": "South",
    "doddakallasandra": "South",
    "electronic city": "South",
    "gottigere": "South",
    "hanumanthnagar": "South",
    "haralur": "South",
    "hongasandra": "South",
    "hsr": "South",
    "hsr layout": "South",
    "hulimavu": "South",
    "isro layout": "South",
    "j p nagar": "South",
    "jayanagar": "South",
    "jonnakunte cross": "South",
    "jp nagar": "South",
    "jp nagar 8th phase": "South",
    "kaggalipura": "South",
    "kaglipura": "South",
    "konanakunte": "South",
    "konanakunte cross": "South",
    "koramangala": "South",
    "kormangala": "South",
    "srinagar": "South",
    "uttarahalli": "South",
    "yelachenahalli": "South",

    "aecs layout": "East",
    "bellandur": "East",
    "brookefield": "East",
    "cv raman nagar": "East",
    "doddanekkundi": "East",
    "domlur": "East",
    "g m palya": "East",
    "gm palya": "East",
    "indiranagar": "East",
    "kadugodi": "East",
    "kaggadasapura": "East",
    "kr puram": "East",
    "kundalahalli": "East",
    "mahadevapura": "East",
    "marathahalli": "East",
    "murugeshpalya": "East",
    "nagondanahalli": "East",
    "old airport road": "East",
    "ramamurthy nagar": "East",
    "sarjapur": "East",
    "sarjapur road": "East",
    "varthur": "East",
    "whitefield": "East",

    "anand nagar hebbal post": "North",
    "batrayanpura": "North",
    "byatarayanapura": "North",
    "hebbal": "North",
    "hebbal kempapura": "North",
    "hennur": "North",
    "jakkur": "North",
    "kodigehalli": "North",
    "kogilu": "North",
    "manyata": "North",
    "nagavara": "North",
    "r t nagar": "North",
    "rt nagar": "North",
    "sahakarnagar": "North",
    "thanisandra": "North",
    "vidyaranyapura": "North",
    "yelahanka": "North",
    "yeshwanthpur": "North",

    "andrahalli": "West",
    "andhrahalli": "West",
    "attiguppe": "West",
    "basaveshwara nagar": "West",
    "basaveshwaranagar": "West",
    "basaveshwarnagar": "West",
    "basaweshwarnagar":"West",
    "chandra layout": "West",
    "kamakshipalya": "West",
    "kengeri": "West",
    "magadi road": "West",
    "malleswaram": "West",
    "malleshwaram": "West",
    "mysore road": "West",
    "nagadevanahalli": "West",
    "nagarbhavi": "West",
    "nayandahalli": "West",
    "nayandhalli": "West",
    "padrayanapura": "West",
    "r r nagar": "West",
    "rajajinagar": "West",
    "rajarajeshwari nagar": "West",
    "rr nagar": "West",
    "sunkadakatte": "West",
    "sunkadkatte": "West",
    "tavarekere": "West",
    "vijayanagar": "West",

    "brigade road": "Central",
    "chamrajpet": "Central",
    "cox town": "Central",
    "cubbon park": "Central",
    "frazer town": "Central",
    "gandhinagar": "Central",
    "majestic": "Central",
    "mg road": "Central",
    "richmond town": "Central",
    "shivajinagar": "Central",
    "ulsoor": "Central",
    "vasanth nagar": "Central",
    "vasanthnagar": "Central",
    "vasanthanagar": "Central",
    "containment": "Central",
}
